{% set name = "numba-stats" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/numba-stats-{{ version }}.tar.gz
  sha256: e1932a349c0d3f6a5988f903a9895ceac6537afb271afe5360aa1ea6005c7c25

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry
  run:
    - numba >=0.50
    - python >=3.6,<4.0
    - scipy >=1.5.0
    - numpy
    - importlib_metadata

test:
  imports:
    - numba_stats
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/numba-stats/
  summary: Fast numba-accelerated versions of common statistical functions
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
