{% set name = "numba-stats" %}
{% set version = "1.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 08c17b63d4174859171e542aff46286e847d642c80856c7b2e5d9d09cb5a10a4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry
  run:
    - numba >=0.50
    - python >=3.6,<4.0
    - scipy >=1.5.0
    - numpy
    - importlib_metadata

test:
  imports:
    - numba_stats
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/numba-stats/
  summary: Fast numba-accelerated versions of common statistical functions
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
