{% set name = "numba-stats" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/numba-stats-{{ version }}.tar.gz
  sha256: f8ba1f301aee295d2f3200bb09f45c0f0f7a53b4ded57f45c6a2a61b3e24f0f8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry
  run:
    - numba >=0.50
    - python >=3.6,<4.0
    - scipy >=1.5.0

test:
  imports:
    - numba_stats
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/numba-stats/
  summary: Fast numba-accelerated versions of common statistical functions
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
