{% set name = "numba-stats" %}
{% set version = "0.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/numba-stats-{{ version }}.tar.gz
  sha256: f9df0ca2c0de61beeee952c75908bb8d7269b24df3bcfb4ed38653406bb9d358

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry
  run:
    - numba >=0.50
    - python >=3.6,<4.0
    - scipy >=1.5.0
    - numpy
    - importlib_metadata

test:
  imports:
    - numba_stats
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/numba-stats/
  summary: Fast numba-accelerated versions of common statistical functions
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
